apiVersion: v1
kind: Service
metadata:
  name: processing-service
  namespace: processing
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: processing
  ports:
    - port: 5000
      targetPort: 5000
