apiVersion: v1
kind: Service
metadata:
  name: alerts-service
  namespace: alerts
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: alerts
  ports:
    - port: 5000
      targetPort: 5000
