apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: processed-earthquakes
  namespace: kafka
  labels:
    strimzi.io/cluster: earthquake-kafka
spec:
  partitions: 3
  replicas: 1
