apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
  namespace: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: query
          image: earthquake-query:local
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: postgres.database.svc.cluster.local
            - name: POSTGRES_DB
              value: earthquakes
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: example
          ports:
            - containerPort: 5000
